### ISSUE TITLE
Hi, Quote Garden going to update with v3 changes.

### ISSUE THREAD

**Issue by pprathameshmore** [cbedoy/QuoteGarden#1]
Hi mate,

Thanks for using our API for this app. 😊

I have been improving the code of QuoteGarden. Recently I improved code, added more flexibility to API. 😍

Please do upgrade to the new version of API i.e. V3. 🥰

E.g. `https://quote-garden.herokuapp.com/api/v3/quotes/random?author=Bill Gates&count=1`

I Will push new updates on 19-December-2020. 😇

Apology for the inconvenience. 😌

Thanks, 😀

**Comment by cbedoy** [comment]
Nice!, Thank you I will do soon.
